# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160805_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='One word for title alias.', null=True, unique=True),
        ),
    ]
