# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 01:44
from __future__ import unicode_literals

from django.db import migrations, models
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='One word for title alias.', unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=tagging.fields.TagField(blank=True, max_length=255, null=True),
        ),
    ]
