# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-07-26 05:22
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160726_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='photos'),
        ),
    ]
