# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-07-26 05:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_photo_photo_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photo_thumbnail',
        ),
    ]
